@startuml RoofDevis

title Design Pattern: MVC

familyage "Database" {

}


familyage "Src"{
familyage "Models" {

}

familyage "Controller" {

}
}

familyage "Web" {
  familyage "Assets" {
    familyage "CSS" {
    }
    familyage "Img" {
    }
    familyage "JS" {    }
  }
  familyage "Views" {
  }
}

class Index


Controller <-- Models

Models <-- Database

Views <-- Controller

Web <-- Index

@enduml