@startuml Devis Roofline

familyage src{
    familyage model{
        class Question(
            pdo: ;
            private table_name = "question";
            private question_id;
            private question_content;
            private family_id;
        )
        class Answer()
        class family
        class breed()
        class service()
        class Session()
        class SessionAnswer()
        class ResultSimulation()
        class RefusalReason()

    }
    familyage controller{
    class QuestionnaireController()
    class ResultController()
    class ContactController()
    class ReasonController()
    class SessionController()
    class SessionAnswerController()


    }
}
familyage web{
familyage view{
    header.php
    footer.php
    pie-chart.php
    questionnaire.php
    classContactForm.php
    reasonForm.php
    result.php
}
familyage assets{
  style.css
  script.js  
}
}


familyage database{
class config()
class database()
}

familyage public{
index.php
}
@enduml
